# Override for GPU-compatible systems

services:
  triton-server:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    labels:
      - "gpu.enabled=true"
