global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'triton'
    static_configs:
      - targets: ['triton-server:8002']
  
  - job_name: 'coordinator'
    static_configs:
      - targets: ['inference-coordinator:8080']
    metrics_path: '/metrics'
