name: "text_classifier"
platform: "onnxruntime_onnx"
max_batch_size: 8
input [
  {
    name: "INPUT_TEXT"
    data_type: TYPE_FP32
    dims: [ 512 ]
  }
]
output [
  {
    name: "OUTPUT_SCORES"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]
default_model_filename: "model.onnx"
