name: "identity_model"
platform: "onnxruntime_onnx"
max_batch_size: 8
input [
  {
    name: "INPUT"
    data_type: TYPE_FP32
    dims: [ 5 ]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [ 5 ]
  }
]
default_model_filename: "model.onnx"
